package com.kessinger.kessinger.model.enums;

public enum Paises {

    AF("Afghanistan"),
    AB("Albania"),
    AL("Algeria"),
    AD("Andorra"),
    AN("Angola"),
    AG("Antigua and Barbuda"),
    AR("Argentina"),
    AM("Armenia"),
    AA("Aruba"),
    AU("Australia"),
    AS("Austria"),
    AZ("Azerbaijan"),
    Bahamas("Bahamas"),
    Bahrain("Bahrain"),
    Bangladesh("Bangladesh"),
    Barbados("Barbados"),
    Belarus("Belarus"),
    Belgium("Belgium"),
    Belize("Belize"),
    Benin("Benin"),
    Bhutan("Bhutan"),
    Bolivia("Bolivia"),
    BosniaHerzegovina("Bosnia and Herzegovina"),
    Botswana("Botswana"),
    Brazil("Brazil"),
    Brunei("Brunei"),
    Bulgaria("Bulgaria"),
    BurkinaFaso("Burkina Faso"),
    Burma("Burma"),
    Burundi("Burundi"),
    Cambodia("Cambodia"),
    Cameroon("Cameroon"),
    Canada("Canada"),
    CaboVerde("Cabo Verde"),
    CentralAfricanRepublic("Central African Republic"),
    Chad("Chad"),
    Chile("Chile"),
    China("China"),
    Colombia("Colombia"),
    Comoros("Comoros"),
    CongoDemocraticRepublicofthe("Democratic Republic of the Congo"),
    CongoRepublicofthe("Republic of the Congo"),
    CostaRica("Costa Rica"),
    CotedIvoire("Cote d`Ivoire"),
    Croatia("Croatia"),
    Cuba("Cuba"),
    Curacao("Curacao"),
    Cyprus("Cyprus"),
    Czechia("Czechia"),
    Denmark("Denmark"),
    Djibouti("Djibouti"),
    Dominica("Dominica"),
    DominicanRepublic("Dominican Republic"),
    TimorLeste("East Timor (Timor-Leste)"),
    Ecuador("Ecuador"),
    Egypt("Egypt"),
    ElSalvador("El Salvador"),
    EquatorialGuinea("Equatorial Guinea"),
    Eritrea("Eritreia"),
    Estonia("Estonia"),
    Ethiopia("Ethiopia"),
    Fiji("Fiji"),
    Finland("Finland"),
    France("France"),
    Gabon("Gabon"),
    Gambia("Gambia"),
    Georgia("Georgia"),
    Germany("Germany"),
    Ghana("Ghana"),
    Greece("Greece"),
    Grenada("Grenada"),
    Guatemala("Guatemala"),
    Guinea("Guinea"),
    GuineaBissau("Guinea Bissau"),
    Guyana("Guyana"),
    Haiti("Haiti"),
    HolySee("Holy See"),
    Honduras("Honduras"),
    HongKong("Hong Kong"),
    Hungary("Hungary"),
    Iceland("Iceland"),
    India("India"),
    Indonesia("Indonesia"),
    Iran("Iran"),
    Iraq("Iraq"),
    Ireland("Ireland"),
    Israel("Israel"),
    Italy("Italy"),
    Jamaica("Jamaica"),
    Japan("Japan"),
    Jordan("Jordan"),
    Kazakhstan("Kazakhstan"),
    Kenya("Kenya"),
    Kiribati("Kiribati"),
    KoreaNorth("North Korea"),
    KoreaSouth("South Korea"),
    Kosovo("Kosovo"),
    Kuwait("Kuwait"),
    Kyrgyzstan("Kyrgyzstan"),
    Laos("Laos"),
    Latvia("Latvia"),
    Lebanon("Lebanon"),
    Lesotho("Lesotho"),
    Liberia("Liberia"),
    Libya("Libya"),
    Liechtenstein("Liechtenstein"),
    Lithuania("Lithuania"),
    Luxembourg("Luxembourg"),
    Macau("Macau"),
    Macedonia("Macedonia"),
    Madagascar("Madagascar"),
    Malawi("Malawi"),
    Malaysia("Malaysia"),
    Maldives("Maldives"),
    Mali("Mali"),
    Malta("Malta"),
    MarshallIslands("Marshall Islands"),
    Mauritania("Mauritania"),
    Mauritius("Mauritius"),
    Mexico("Mexico"),
    Micronesia("Micronesia"),
    Moldova("Moldova"),
    Monaco("Monaco"),
    Mongolia("Mongolia"),
    Montenegro("Montenegro"),
    Morocco("Morocco"),
    Mozambique("Mozambique"),
    Namibia("Namibia"),
    Nauru("Nauru"),
    Nepal("Nepal"),
    Netherlands("Netherlands"),
    NewZealand("New Zealand"),
    Nicaragua("Nicaragua"),
    Niger("Niger"),
    Nigeria("Nigeria"),
    Norway("Norway"),
    Oman("Oman"),
    Pakistan("Pakistan"),
    Palau("Palau"),
    PalestinianTerritories("Palestinian Territories"),
    Panama("Panama"),
    PapuaNewGuinea("Papua New Guinea"),
    Paraguay("Paraguay"),
    Peru("Peru"),
    Philippines("Philippines"),
    Poland("Poland"),
    Portugal("Portugal"),
    Qatar("Qatar"),
    Romania("Romania"),
    Russia("Russia"),
    Rwanda("Rwanda"),
    SaintKittsandNevis("Saint Kitts and Nevis"),
    SaintLucia("Saint Lucia"),
    SaintVincentandtheGrenadines("Saint Vincent and the Grenadines"),
    Samoa("Samoa"),
    SanMarino("San Marino"),
    SaoTomeandPrincipe("Sao Tome and Principe"),
    SaudiArabia("Saudi Arabia"),
    Senegal("Senegal"),
    Serbia("Serbia"),
    Seychelles("Seychelles"),
    SierraLeone("Sierra Leone"),
    Singapore("Singapore"),
    SintMaarten("Sint Maarten"),
    Slovakia("Slovakia"),
    Slovenia("Slovenia"),
    SolomonIslands("Solomon Islands"),
    Somalia("Somalia"),
    SouthAfrica("South Africa"),
    SouthSudan("South Sudan"),
    Spain("Spain"),
    SriLanka("Sri Lanka"),
    Sudan("Sudan"),
    Suriname("Suriname"),
    Swaziland("Swaziland"),
    Sweden("Sweden"),
    Switzerland("Switzerland"),
    Syria("Syria"),
    Taiwan("Taiwan"),
    Tajikistan("Tajikistan"),
    Tanzania("Tanzania"),
    Thailand("Thailand"),
    Togo("Togo"),
    Tonga("Tonga"),
    TrinidadandTobago("Trinidad and Tobago"),
    Tunisia("Tunisia"),
    Turkey("Turkey"),
    Turkmenistan("Turkmenistan"),
    Tuvalu("Tuvalu"),
    Uganda("Uganda"),
    Ukraine("Ukraine"),
    UnitedArabEmirates("United Arab Emirates"),
    UnitedKingdom("United Kingdom"),
    UnitedStates("United States of America"),
    Uruguay("Uruguay"),
    Uzbekistan("Uzbekistan"),
    Vanuatu("Vanuatu"),
    Venezuela("Venezuela"),
    Vietnam("Vietnam"),
    Yemen("Yemen"),
    Zambia("Zambia"),
    Zimbabwe("Zimbabwe");


    private String pais;

    public String getPais() {
        return pais;
    }

    Paises(String pais) {
        this.pais = pais;
    }

}
